### ISSUE TITLE
Slug form is not a valid input "resin.models.application.create() "

### ISSUE THREAD

**Issue by mkorakakis** [resin-io/resin-sdk#101]
It appears that the slug form doesn't work.
Output while running the example from the help section:
```
Unhandled rejection ResinInvalidDeviceType: Invalid device type: raspberry-pi
```
Meanwhile, if i replace the raspberry-pi in the code with Raspberry Pi it works as it should.

**Comment by jviotti** [comment]
This is a documentation issue. I'll update the docs to reflect the need of display names. Thanks for catching it!
