### ISSUE TITLE
Integrate API Keys with SDK

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-sdk#143]
> you first start with your auth token and do a POST request to https://api.resin.io/application/#{application.id}/generate-api-key (sending the token in the Auth header) - see https://github.com/resin-io/resin-sdk/blob/397c0e5dc570c3d094561b6d3d27ae3254d9a141/build/models/application.js#L324 for example usage
> the server should reply with an API key (json-encoded string, so you may need to strip an extra pair of quotes)
> 
> after that you add ?apikey=API_KEY to all your API requests and _not_ send the token header anymore

**Comment by jviotti** [comment]
This should support passing the API key as an environment variable.

**Comment by jviotti** [comment]
Plan:

- [ ] Add `apiKeyVariable` setting to resin-io/resin-settings-client.
- [ ] Refactor resin-io/resin-request to use API Keys, using the new resin-io/resin-settings-client to find it.
- [ ] Upgrade resin-io/resin-request to the new version in resin-io/resin-pine.
- [ ] Upgrade resin-io/resin-request and resin-io/resin-pine in resin-io/resin-sdk.
- [ ] Remove authentication utilities from resin-io/resin-sdk to make it stateless.

**Comment by nghiant2710** [comment]
@jviotti `RESIN_API_KEY` is system variable (RESIN_ prefix) so user won't be able to set it on the Dashboard. I suggest changing to `APPLICATION_API_KEY`

**Comment by pimterry** [comment]
API keys (named user api keys, at least) are fully supported in the latest SDK, closing.
