### ISSUE TITLE
"Last online x hours ago" and "Came online x hours ago" 

### ISSUE THREAD

**Issue by benoitguigal** [resin-io/resin-sdk#166]
Is it possible to get x ? I have only seen `isOnline` method call

**Comment by Page-** [comment]
It should be accessible via the device's `last_seen_time` property, if `is_online` is true then it's when it came online, if false then it's when it went offline

**Comment by benoitguigal** [comment]
Like this ?
```
resin.models.device.get(uuid, function(error, device) {
	if (error) throw error;
 	console.log(device.last_seen_time);
 });
```

**Comment by Page-** [comment]
Yes, that should work (I haven't tried myself though).  If you use `console.log(new Date(device.last_seen_time));` it will be formatted as a date (eg `Wed Jan 06 2016 14:10:49 GMT+0000 (GMT Standard Time)`) rather than a timestamp (eg `1452089463314`)

**Comment by benoitguigal** [comment]
ok perfect thanks
