### ISSUE TITLE
Add a function to reboot a device

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-sdk#195]
See `/v1/reboot` in the [Supervisor API](http://docs.resin.io/#/pages/runtime/supervisor-api.md#post-v1-reboot).

From https://github.com/resin-io/resin-cli/issues/319

**Comment by drjasonharrison-vp-eio** [comment]
current URL: https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1reboot
