### ISSUE TITLE
Support for websockets ?

### ISSUE THREAD

**Issue by benoitguigal** [resin-io/resin-sdk#203]
Is it possible to receive the status of a device in real time through web sockets ?

**Comment by jviotti** [comment]
@benoitguigal Sadly not yet. There has been discussions on providing a Resin real-time API (mainly oriented to logs though), so for now the only option is polling.

Assuming your concern is speed, you might be able to optimise your request by filtering for the device property you're interested in, so you don't get unnecessary info, and thus extra network overhead.

For this, you'll have to use the low-level [resin-pine](https://github.com/resin-io-modules/resin-pine) module, which is used internally by the SDK. This request queries a device but only returns the `is_online` property:

```coffee
pine = require('resin-pine')

return pine.get
  resource: 'device'
  options:
    expand: 'application'
    filter:
      uuid: <your device uuid>
    select: [
      'is_online'
    ]
```

The promise will resolve with an object containing only the selected property.

Let me know if you need any help with this!

**Comment by Page-** [comment]
I would highly recommend also only selecting the application properties you're interested in if expanding, eg
```coffee
pine.get
  resource: 'device'
  options:
    expand: application: $select: [ 'id', 'app_name' ]
    filter:
      uuid: <your device uuid>
    select: [
      'is_online'
    ]
```

**Comment by benoitguigal** [comment]
Ok I will give it a try. What would you recommend as a polling interval ?

**Comment by jviotti** [comment]
@benoitguigal I guess it depends on your use case, but as an example our web dashboard polls for devices in a 3 seconds interval.
