### ISSUE TITLE
Decide on the new device registration process

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-sdk#232]
It (starting from `resin-register-device@3`) needs a provisioning key which will make it unusable for the ghost devices creation used by the CLI.

Decision to be made after we publish the browser-compat SDK.

NB: it's easy to prohibit this method in the browser, but
a) we need the provisioning keys for node.js tests
b) this method is used for inserting fixtures for other tests valid for the browser, like moving the device

**Comment by pimterry** [comment]
Fixed in 6.0.0.
