### ISSUE TITLE
Missing/wrong factory argument errors aren't very helpful

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-sdk#251]
In the new factory-method build, the errors you get if you miss an argument to the factory aren't very helpful.

* No `apiUrl` argument:
  `TypeError: Parameter "url" must be a string, not undefined`
  Note that `url` != `apiUrl` - this error comes from Resin-Pine.
  Arguably this should just default to our prod API endpoint anyway?

* No `dataDirectory` argument in Node:
  `TypeError: Path must be a string. Received null` (what?)

* No `imageMakerUrl` argument:
  No error, but the docs says it's required - presumably something breaks later?
  Arguably this should just default to our prod API endpoint anyway?

* No options argument provided at all:
  `TypeError: Cannot read property 'isBrowser' of undefined`
  We should default to an empty object to make things nice and easy for devs.

**Comment by emirotin** [comment]
> imageMakerUrl

Is currently only used for OS downloads (not used in the browser).

**Comment by pimterry** [comment]
Closing, since we now have defaults for all these parameters, so this isn't a problem any more.
