### ISSUE TITLE
Browser version fails throws exception with webpack HMR.

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-sdk#256]
I'm giving the new browser version a spin with a react and running into an exception when Hot module replacement is active. 

```
Error in ./~/resin-sdk/build/resin.js
Module not found: 'resin-settings-client' in /Users/gaudi/work/resin-1984/node_modules/resin-sdk/build

 @ ./~/resin-sdk/build/resin.js 85:15-47
```

Still trying to debug, but if you have any ideas, send em my way.

@pimterry @emirotin

**Comment by emirotin** [comment]
I think I know why. The module is likely loaded in non-browser environment

But it highlights a good problem. We've removed this module from the dependencies but we actually shouldn't. It's re-exposed in Node.js here: https://github.com/resin-io/resin-sdk/blob/593bd1f60ec14c78a0c9d4afb8cba3fa7ed97399/lib/resin.coffee#L70

We should return it to dependencies.

**Comment by emirotin** [comment]
I will also more carefully inspect the usage of settings now.
