### ISSUE TITLE
Refused to set unsafe header "accept-encoding"

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-sdk#257]
I get `Refused to set unsafe header "accept-encoding"` thrown for each request.

**Comment by emirotin** [comment]
Interesting. Why don't we see them in the tests (as well as in my demo project)? Does it actually stop it from working or shows a warning but still sends the requests?

**Comment by emirotin** [comment]
But I know that it happens here https://github.com/resin-io-modules/resin-request/search?utf8=%E2%9C%93&q=accept-encoding

**Comment by emirotin** [comment]
Moved to https://github.com/resin-io-modules/resin-request/issues/91, closing here.
