### ISSUE TITLE
Why do we require `apiUrl` argument?

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-sdk#258]
Surely 99% of the time it's going to be `https://api.resin.io/`? If we set it as the default then users could just pass and empty `opts` object.

**Comment by lekkas** [comment]
I believe this has to do with having the ability to pass the `RESINRC_RESIN_URL=resinstaging.io` and `RESINRC_RESIN_URL=resindev.io` variables to point `resin-cli`/`resin-sdk` to staging/devenv respectively

**Comment by emirotin** [comment]
We could still set the default, it makes sense for the majority of use-cases

**Comment by pimterry** [comment]
See #251 - I think that covers this and a few other bits we could improve the the api usability side.

**Comment by lekkas** [comment]
Uh, sorry I see what you meant now. Yeah it definitely makes sense to set this as a default value.
