### ISSUE TITLE
Add versionist for automatic changelog generation. 

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-sdk#261]
https://github.com/resin-io/versionist

Also need to extract some info from https://github.com/resin-io/hq/blob/master/process/Commit_and_PR_Guidelines.md for commit msg format.

**Comment by pimterry** [comment]
Related to https://github.com/resin-io/resin-sdk/pull/301: we now automatically deploy tagged versions to npm, so versionbot will be automatically generating npm releases once it's in place.

**Comment by pimterry** [comment]
Done!
