### ISSUE TITLE
Prevent users from setting environment variables that are invalid

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/resin-sdk#264]
connects to:
https://github.com/resin-io/hq/issues/614
https://github.com/resin-io/resin-ui/issues/377

You should only be able to set an environment variable if:

- It doesn't start with a digit
- It only contains alphanumeric characters and underscore

**Comment by LucianBuzzo** [comment]
http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

**Comment by pimterry** [comment]
Fixed in v6.6.1
