### ISSUE TITLE
Need the clear logs functionality

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-sdk#272]
Needs to be implemented here https://github.com/resin-io/resin-device-logs/issues/18.
Updating that module to use pubnub@^4 would also be nice.

Also the SDK docs have to mention the unsubscribe method that's already supported.

**Comment by pimterry** [comment]
@emirotin I think this now be closed - is that right?

**Comment by emirotin** [comment]
The first two points are done indeed.
Not sure about the docs
