### ISSUE TITLE
Add device GPS locations 

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-sdk#282]
Allow same functionality as offered from the dashboard.

**Comment by alexandrosm** [comment]
@lucianbuzzo -- this is the kind of thing i was talking about when
discussing the sdk :)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by LucianBuzzo** [comment]
@alexandrosm Yep this is a perfect example! 
The TLDR -  ideally the SDK should be able to reflect changes in the resin SBVR model without requiring new code to be written.

**Comment by pimterry** [comment]
This is a planned part of https://github.com/resin-io/resin-ui/issues/400#issuecomment-285693667, and I'm expecting to get this in early this week.

(SDK support for the gps locations I mean, not auto-generating the SDK, although I totally agree that that'd be a good thing :+1:)

**Comment by pimterry** [comment]
Fixed in 6.0.0.
