### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-sdk#307]
Step 1: resin-request
Step 2: pubnub http://stackoverflow.com/questions/36992912/cannot-get-node-js-to-connect-to-pubnub-from-corporate-network in the resin-device-logs
Step 3: use the resin-settings-client to get the proxy config and pass to the deps

**Comment by pimterry** [comment]
Is this only going to be configurable through resin config? It'd be nice if we could configure it with the normal `HTTP_PROXY`, `HTTPS_PROXY` env vars, which are a bit more standard & intuitive imo.

Whatever's easiest of course, we can always extend to do that later if this is easier.

Also maybe useful or interesting (I'm not sure if you/somebody mentioned this before?) I've just found https://www.npmjs.com/package/global-tunnel, which automatically overrides anything using `http` or `request`. That might cover all the above automatically? Not sure.

**Comment by emirotin** [comment]
For now it's going to be the standard resin config, but it can be extended later of course

The global tunnel is interesting but needs some investigation, I'm going to try my current approach and check the global-tunnel later.

**Comment by pimterry** [comment]
What else needs doing on this @emirotin, if anything?

**Comment by emirotin** [comment]
Ah nothing I think, it ended up being in the CLI, let's close this one.
