### ISSUE TITLE
Edge case: short UUID can be mistakenly identified as an appID

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-sdk#334]
If the short ID only has number digits (`8928570`) `resin.models.has()` will fail to find the device - looks like this is an edge case in 

- https://github.com/resin-io/resin-sdk/blob/master/lib/models/device.coffee#L64
- https://github.com/resin-io/resin-sdk/blob/master/lib/util/index.coffee#L18

**Comment by pimterry** [comment]
Duplicate, this is actually a CLI issue over here: https://github.com/resin-io/resin-cli/issues/489

Super annoying though, I know. I'm going to sort it properly soon, promise.
