### ISSUE TITLE
Move `fixDeviceEnvVarNameKey` logic from the UI to the SDK

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/resin-sdk#336]

**Comment by pimterry** [comment]
Strangely the SDK already has this logic, so I'm not totally sure what this ticket would require. More excitingly, with multicontainer we're going to fix the model properly so this isn't necessary in the first place. 

Regardless, this ticket can go. Watch this space: https://www.flowdock.com/app/rulemotion/resin-tech/threads/AUkf8KA09AEa2nVIk-EdUyUeng_
