### ISSUE TITLE
Creating an application with a discontinued device type should fail

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-sdk#358]
HQ: resin-io/hq#785
See: resin-io/resin-ui#998

**Comment by thgreasi** [comment]
As far as I could find in the already deprecated repos, [the condition seems to be `state == 'discontinued'`](https://github.com/resin-os/resin-parallella/blob/73583416a7289cc709a9e74f20dd8caef3e6c716/parallella-hdmi-resin.coffee#L11).

**Comment by pimterry** [comment]
@thgreasi good point, updated.

**Comment by thgreasi** [comment]
@pimterry I also think that we currently [do not filter at all the supported device types](https://github.com/resin-io/resin-sdk/blob/c7b6bd60f74660f3df05ec436269b75913afc13c/lib/models/device.coffee#L1159-L1162).
The interested question is whether we should also filter out both the `DEPRECATED` (the UI already does this manually) and the `discontinued` states. (Loved the inconsistent casing!)

**Comment by pimterry** [comment]
I think we still don't want to do any filtering there, even after this change. The UI and other places still need to know about these discontinued device types, so they can handle existing applications using it, it's only in application creation behaviour that anything major will change (plus potential UI changes in how we display these device types).

**Comment by thgreasi** [comment]
OK!

**Comment by pimterry** [comment]
Fixed in 7.0.0
