### ISSUE TITLE
models.os.getMaxSatisfyingVersion cannot return a dev image

### ISSUE THREAD

**Issue by Page-** [resin-io/resin-sdk#422]
This is due to `semver.maxSatisfying(['2.0.8+rev1.prod','2.0.8+rev1.dev'], '2.0.8+rev1.dev')` returning `'2.0.8+rev1.prod'`, so even with maximum specificity you still get given the prod image (presumably because `p` > `d` and build metadata is ignored for comparsions)

**Comment by pimterry** [comment]
Fixed and released in 7.0.1
