### ISSUE TITLE
isOnline method should use both "device_is_online" and "service_last_connectivity_event" to infer VPN connection

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-sdk#428]
isOnline method should use the following logic going forward:
```
If device_is_online is true and the service_last_connectivity_event is less than 30 seconds, then the device is online
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3yw1)

**Comment by flesler** [comment]
This is the related spec: https://github.com/resin-io/hq/pull/627
Discussion was here: https://www.flowdock.com/app/rulemotion/resin-tech/threads/XQ66Jd1lD6sFvOS3UbbIXBepdtN

At one point in the thread Petros explains the conditions to be online.

**Comment by pimterry** [comment]
We're now going to solve this in the API itself (https://github.com/resin-io/resin-api/issues/645), so this can be closed.
