### ISSUE TITLE
Image download cache

### ISSUE THREAD

**Issue by telphan** [resin-io/resin-sdk#440]
It would be nice to have the image cache for multiple downloads.

**Comment by pimterry** [comment]
This already exists in https://github.com/resin-io-modules/resin-image-manager, which wraps the SDK, and gets used in the CLI.

I'm a bit cautious about building it into the SDK itself - as much as possible I'd like the SDK not to have side effects, and maintaining a (potentially pretty massive) on-disk cache is a fairly major side effect. Does resin-image-manager work for you?

**Comment by pimterry** [comment]
Confirmed that in Flowdock that we're happy with this (https://www.flowdock.com/app/rulemotion/resin-frontend/threads/6vnA2BTPA_YdSGg3D8KueKO7ZpD), closing.
