### ISSUE TITLE
Calls to models.application show do not include collaborators' apps

### ISSUE THREAD

**Issue by nurikabe** [resin-io/resin-sdk#476]
Authing using email/password, calls to `models.application` only return results if the auth user is the original owner of the applications; not a collaborator.

This seems to differ from the REST API.  If I curl using the token of a collaborator I can see all applications for which the collaborator has access.

**Comment by thgreasi** [comment]
Hi,
This seems pretty reasonable. Let me do a research about the reason that made us also filter on the current user ID.

**Comment by thgreasi** [comment]
@pimterry I totally agree that this should be in the MC release.
I think I will not be able to pick this up until next week. Will check back with you when I'll have some time for this.

**Comment by pimterry** [comment]
@CameronDiver is going to handle this as part of some CLI work he's doing
