### ISSUE TITLE
Application tags?

### ISSUE THREAD

**Issue by nurikabe** [resin-io/resin-sdk#485]
The SDK indicates that we can create tags associated with an application rather than just per device:

https://docs.resin.io/reference/sdk/node-sdk/#application-tags-code-object-code-

Seems like this may not be working though?  If not, curious if there a plan to implement this.

**Comment by nurikabe** [comment]
Ah, correction:  This does seem to work, however the Resin.io web interface doesn't display them.

**Comment by pimterry** [comment]
@thgreasi - are we definitely not displaying application tags anywhere in the dashboard right now? Are there plans for that coming?

**Comment by thgreasi** [comment]
@pimterry @nurikabe I can confirm that we are not displaying application tags anywhere in the dashboard at the moment, but it's in our immediate plans to start doing so.
For now it's just an SDK feature that we can use to group our apps. Eg let's saw that you want to group two apps that run the same code but one is on RPi 3 while the other one on RPi zero W.

I will take note on the UI request.
Can this be closed @nurikabe ?

**Comment by nurikabe** [comment]
Thanks, closing.  If application-level tags are going to be supported in the dashboard then we'll start to use them.

**Comment by thgreasi** [comment]
Hi @nurikabe,
We would like to let you know that the latest release of the balenaCloud dashboard includes a table view for the applications, which now also supports application tags.
