### ISSUE TITLE
Environment variables not support in multicontainer

### ISSUE THREAD

**Issue by jgentes** [resin-io/resin-sdk#488]
I get this error when I try to set an environment variable on my multi-container app: `Unhandled rejection ResinRequestError: Request error: Bad Request`

Here's my code:
```
var resin = require('resin-sdk')();

resin.auth.loginWithToken(process.env.RESIN_AUTH, function(error) {
    if (error) throw error;
    resin.models.environmentVariables.create('my_app', 'RELEASE_SHA', 'test');
});
```

I see the same error when I try to perform the operation using resin-cli. Any thoughts?

**Comment by pimterry** [comment]
Ah, yes. I can't be certain, but I strongly suspect this is the main remaining part of #411 - multicontainer support in the SDK is not fully complete yet, and doesn't support env vars in multi containers apps, but we're working on it! Watch this space.

**Comment by thgreasi** [comment]
@jgentes do you have more than one containers on that application?
