### ISSUE TITLE
Add method to get container state w/ multicontainer

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/resin-sdk#489]
Currently it seems that there's no method available to interrogate the state of a device's containers, i.e. whether they're downloading an update.

See https://forums.resin.io/t/multicontainer-api-for-download-status/2905
Connects To: #411 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_avor)

**Comment by pimterry** [comment]
This is actually complete, it's just only available on the beta release of the SDK, which supports multicontainer.

I'm going to close this for now - if you're looking for this method before the official MC SDK release, you need to:

```
npm install resin-sdk@beta
```

and then use [`resin.models.device.getWithServiceDetails`](https://github.com/resin-io/resin-sdk/blob/multicontainer/DOCUMENTATION.md#resin.models.device.getWithServiceDetails).

Note that the MC SDK is still in a state of flux though: some features aren't yet complete (notably including environment variables), and you'll want to pin a specific release as there may be breaking changes before the final release.
