### ISSUE TITLE
Fix `expots` typo

### ISSUE THREAD

**Issue by dimitrisnl** [resin-io/resin-sdk#506]
https://github.com/resin-io/resin-sdk/blob/master/lib/settings.coffee#L22

**Comment by dimitrisnl** [comment]
Minor thing I noticed while pinpointing https://github.com/resin-io/resin-sdk/issues/501

**Comment by thgreasi** [comment]
Oh my... How does this work all this time? :alien: :satellite: 
How about targeting the PR against the MC branch?

**Comment by thgreasi** [comment]
Oh cool, just saw that you did :)

**Comment by dimitrisnl** [comment]
Yeah, I mistakenly tagged you in the issue instead.
