### ISSUE TITLE
Create a standardised set of Error subclasses

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-sdk#6]
Use them throughout the SDK and document them accordingly.

**Comment by Page-** [comment]
Are you planning to use https://github.com/resin-io/typed-error for this?

**Comment by jviotti** [comment]
@Page- Sure. I used to have some custom `TypedError` errors, but remove them as I wanted to plan this better.

**Comment by jviotti** [comment]
Set of custom error messages created and used trough the whole SDK. Documentation pending.
