### ISSUE TITLE
Unauthorized request

### ISSUE THREAD

**Issue by benoitguigal** [resin-io/resin-sdk#98]
```
> resin.auth.loginWithToken(myToken, function(err){console.log(err)})
null 
> resin.auth.isLoggedIn(function(err, isloggedIn){console.log(isloggedIn)})
true 
> resin.auth.whoami(function(err, me){console.log(me)})
gh_benoitguigal 
> resin.models.device.isOnline('resin_device_uuid', function(err, isOnline){console.log(err))}
{ [ResinRequestError: Request error: Unauthorized]
  body: 'Unauthorized',
  name: 'ResinRequestError',
  message: 'Request error: Unauthorized' }
```
I get the same error with any methods. It was working this morning so maybe there is some kind of throttling ?

**Comment by jviotti** [comment]
@benoitguigal Can you try making use of the just released `resin-sdk` v2.3.0, which has the changes required to auto refresh the token? You might need to copy the token from the preferences page again, since it's invalidated in a few hours.

**Comment by benoitguigal** [comment]
Ok will do. So if I understand well the token from the preferences page is invalidated in few hours ?

**Comment by jviotti** [comment]
@benoitguigal That's right. Resin SDK v2.3.0 includes logic to automatically refresh your locally saved token so you don't have to refresh yourself from the preferences page every time.

**Comment by Page-** [comment]
It should take 7 days to expire, so it shouldn't have affected you in this timeframe :S

**Comment by benoitguigal** [comment]
I logged in from a different host with the same token, can it be related ?

**Comment by jviotti** [comment]
@Page- Ah ok, though the token was invalidated in a few hours interval.

I've tried with my account and with a brand new account (without 2FA, etc) and get a device not found error, as expected:

```sh
ResinDeviceNotFound: Device not found: resin_device_uuid
```

@benoitguigal Can you try:

```sh
$ curl --header "Authorization: Bearer xxx" https://api.resin.io/whoami
```

Replacing `xxx` with the token you're using in the example?

**Comment by benoitguigal** [comment]
I am receiving a new token ^^ with `benoit` appended at the end.

**Comment by jviotti** [comment]
@benoitguigal If `/whoami` returned successfully that means that the token is indeed valid, therefore it's weird that you get an Unauthorised error.

Can you try running `resin.models.device.isOnline()` by first setting your token to the token returned by `/whoami`?

**Comment by benoitguigal** [comment]
Yep now it is working with the brand new token ;-).  I think ma first token was invalidated for some reason, hence the error. 
Other question: why is a new token generated each time I reload my preferences page ?

**Comment by jviotti** [comment]
@benoitguigal Sounds good. I believe the web application updated the displayed token every time to reduce your changes of making use of a token that is close to be invalidated, as a way to keep you safe, as the SDK.

**Comment by jviotti** [comment]
@benoitguigal I'll close this issue given that the latest SDK version already has token self update functionality which should prevent you from having the same error again. Please feel free to reopen if the issue persists!

**Comment by benoitguigal** [comment]
yes cool !
